name = "expence-tracker"
compatibility_date = "2026-07-20"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "expence-tracker"
database_id = "7c14e54f-4fa7-4fcf-ac22-2287aeb00a6a"

[[r2_buckets]]
binding = "FILES"
bucket_name = "expence-tracker-files"
